server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: servico_processamento

  # settings jdbc h2 em yml
  datasource:
    url: jdbc:h2:mem:pesquisa_publica
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # settings for h2 console
  h2:
    console:
      enabled: true
