POST {{pesquisa-publica}}/respostas
Content-Type: application/json

{
  "idPesquisa": 1,
  "respondedor": {
    "nome": "João da Silva",
    "email": "joao.silva@example.com",
    "idade": 35
  },
  "respostas": [
    {
      "id": 10
    },
    {
      "id": 8
    }
  ]
}
